
[window]
opacity = 0.76
decorations = "Full"
decorations_theme_variant = "Dark"
dimensions = { columns = 80, lines = 80 }

  [window.padding]
  x = 8
  y = 8

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[font]
size = 10

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[general]
import = [
	"~/alacritty-theme/themes/soy_custom.toml"
]

# me likey 	"~/alacritty-theme/themes/horizon_dark.toml"
# me likey  "~/alacritty-theme/themes/Mariana.toml"
