import = [
  "/home/hitori/.npm/_npx/808b709e6234a442/node_modules/alacritty-themes/themes/Kitty.toml"
]

[window]
opacity = 0.94
decorations = "Full"
decorations_theme_variant = "Light"

  [window.padding]
  x = 10
  y = 10

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[font]
size = 10

  [font.normal]
  family = "MartianMono NFM"
  style = "Regular"
