
[window]
opacity = 1
decorations = "Full"
decorations_theme_variant = "Light"
dimensions = { columns = 80, lines = 80 }

  [window.padding]
  x = 10
  y = 10

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[font]
size = 14

  [font.normal]
  family = "Ubuntu Mono"
  style = "Regular"

[general]
import = [
  "/home/hitori/.npm/_npx/808b709e6234a442/node_modules/alacritty-themes/themes/Kitty.toml"
]
