
[window]
opacity = 0.98
decorations = "Full"
decorations_theme_variant = "Dark"
dimensions = { columns = 80, lines = 80 }

  [window.padding]
  x = 16
  y = 16

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[font]
size = 12

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[general]
import = [
	"~/alacritty-theme/themes/soy_custom.toml"
]

# me likey 	"~/alacritty-theme/themes/horizon_dark.toml"
# me likey  "~/alacritty-theme/themes/Mariana.toml"
