[window]
opacity = 0.85
decorations = "Full"
decorations_theme_variant = "Dark"

  [window.dimensions]
  columns = 80
  lines = 80

  [window.padding]
  x = 16
  y = 16

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[font]
size = 14

  [font.normal]
  family = "BlexMono Nerd Font Mono"
  style = "Regular"

# [general]
# import = [
#   "/home/sleepy/.config/alacritty/themes/themes/dracula.toml"
# ]
