#!/bin/bash

resp=$(acpi -b)

bat_perc=$(echo $(acpi -b) | grep -oP '\d+(?=%)')

crit_perc=30

while true; do

        if [ "$bat_perc" -le "$crit_perc" ] && [[ "$resp" == *"Discharging"* ]]; then
                notify-send -t 60000 -u critical "Low battery: $bat_perc%

yeaaa you should proooobably charge before it dies. like... right now? charge it. now. CHARGE. CHARGE ME. GIVE ME FOOD YOU FUCKER"
        fi

        sleep 60
done
