#!/bin/bash

bat_status=$(acpi -b | awk '{print $3}' | sed 's/,//')

bat_perc=$(acpi -b | awk -F'[,%]' '{print $2}' | sed 's/^ *//')

crit_perc=90

echo this is bat_status
echo ${bat_status}

echo this is bat_perc
echo ${bat_perc}

echo this is crit_perc
echo ${crit_perc}

while true; do

					if [ ${bat_perc} -le "$crit_perc" ] && [[ ${bat_status} == "Discharging" ]]; then
						echo FUCK
hyprctl notify -1 10000 "rgb(ff1ea3)" "CHARGE MEE PLWEAASESEEE"
        fi

					bat_status=$(acpi -b | awk '{print $3}' | sed 's/,//')
        sleep 20
done

