#!/bin/bash

while true; do
    battery=$(upower -i "$(upower -e | grep BAT)" | grep -E "percentage" | awk '{print $2}' | tr -d '%')
    if [ "$battery" -le "40" ]; then
	notify-send -u critical "Low Battery" "Battery is at ${battery}%"
        sleep 240
    else
        sleep 120
    fi
done
