#!/bin/bash

swayidle -w \
  timeout 10 'swaylock --font "CaskaydiaMono NF" -i "~/added_bgs/wallhaven-9oxjvd.png"' \
        timeout 15 'swaymsg "output * dpms off"' \
                resume 'swaymsg "output * dpms on"' \
        before-sleep 'swaylock --font "CaskaydiaMono NF" -i "~/added_bgs/wallhaven-9oxjvd.png"'
